### ISSUE TITLE
组件样式被重复引入，导致样式覆盖的问题

### ISSUE THREAD

**Issue by lanrenbulan** [iczer/vue-antd-admin#81]
很抱歉，在这里问了一个与该库不直接相关的问题。

如果有空，麻烦帮看下这个问题：

https://github.com/vueComponent/ant-design-vue-pro/issues/831

谢谢！

**Comment by iczer** [comment]
能不能提供下复现的链接

**Comment by iczer** [comment]
尝试把 ant-design-pro-vue 中 global.less 样式中这一行代码替换掉。

```diff
- @import '~ant-design-vue/es/style/themes/default.less'
+ @import '~ant-design-vue/dist/antd.less'
```

**Comment by lanrenbulan** [comment]
我试了下还是不行，不懂样式为什么会被重复引入

**Comment by iczer** [comment]
我这边是拿 ant-design-pro-vue 基础表单页面做的测试，是可以生效的哦
![批注 2020-06-29 114519](https://user-images.githubusercontent.com/13096697/85970893-578e5980-b9fe-11ea-80a5-9745c758ca58.png)
你修改后刷新下页面，或者重启下服务看看，如果还不行，可能是你项目里的其他样式的影响了

**Comment by iczer** [comment]
我这边是克隆 ant-design-vue-pro 项目，然后只修改了global.less 文件，测试是没问题的
```less
//@import '~ant-design-vue/es/style/themes/default.less';
@import '~ant-design-vue/dist/antd.less';
html,
body,
#app, #root {
  height: 100%;
}

```
