### ISSUE TITLE
右侧菜单展开收缩时，Vue图标抖动喵

### ISSUE THREAD

**Issue by yihuishou** [iczer/vue-antd-admin#9]
抖抖抖~~ 抖到头发没有

**Comment by iczer** [comment]
(￣▽￣)~*，哈哈，眼力可以

**Comment by myronlau** [comment]
看了看，是h1的字体导致的，如果改成18px就不会抖了，虽然参照了Ant-Design-Pro的样式，但是logo大小好像不一样，就导致了一样的样式但是效果有点不同

**Comment by iczer** [comment]
已修复：[0ab1565](https://github.com/iczer/vue-antd-admin/commit/0ab1565fdf8a951c28abdbc529367dbd6620bcd5)
试过改字体和logo大小，在部分分辨率屏幕上仍会出现抖动情况。
最终解决方案，给 .logo > h1 添加如下样式属性：
```css
.logo > h1{
   height: 32px;
   line-height: 32px;
   vertical-align: middle;
}
```
